import { useNavigation, useRouter } from 'expo-router';
import { useEffect } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

type SectionProps = { title: string; children: React.ReactNode };

function Section({ title, children }: SectionProps) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function Body({ children }: { children: React.ReactNode }) {
  return <Text style={styles.body}>{children}</Text>;
}

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <View style={styles.bulletRow}>
      <Text style={styles.bulletDot}>·</Text>
      <Text style={styles.bulletText}>{children}</Text>
    </View>
  );
}

export default function PrivacyScreen() {
  const navigation = useNavigation();
  const router = useRouter();

  useEffect(() => {
    navigation.setOptions({ headerShown: false });
  }, [navigation]);

  return (
    <SafeAreaView style={styles.container}>

      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} activeOpacity={0.7}>
          <Text style={styles.backText}>← BACK</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>PRIVACY POLICY</Text>
        <View style={{ width: 60 }} />
      </View>

      <ScrollView style={styles.scroll} showsVerticalScrollIndicator={false}>
        <View style={styles.content}>

          <Text style={styles.updated}>Last updated: March 2026</Text>

          <Body>
            Double Yellow ("we", "us", "our") is committed to protecting your personal data and respecting your privacy. This policy explains what data we collect, why we collect it, and your rights under UK GDPR and the UK Data Protection Act 2018.
          </Body>

          <Section title="1. WHO WE ARE">
            <Body>
              Double Yellow is a community parking warden alert app. For the purposes of data protection law, we are the data controller for personal data collected through this app. You can contact us about any privacy matter at: contact@doubleyellow.app
            </Body>
          </Section>

          <Section title="2. WHAT DATA WE COLLECT">
            <Body>We collect the following personal data when you use Double Yellow:</Body>
            <Bullet>Email address — provided when you register, used solely for authentication and account recovery.</Bullet>
            <Bullet>Username — a display name you choose. This is visible to other users on the leaderboard and thank-you screens. Do not use your real name or email as your username.</Bullet>
            <Bullet>Profile photo — optional. Stored securely if you choose to upload one.</Bullet>
            <Bullet>Location data — GPS coordinates are recorded when you activate parking protection and when you submit a warden sighting. These are used to match alerts to nearby parked users.</Bullet>
            <Bullet>Warden report data — the time, location, and optional photo you submit when reporting a warden.</Bullet>
            <Bullet>Device push token — a unique identifier generated by your device, used solely to deliver warden alerts to your phone via push notification.</Bullet>
            <Bullet>In-app points and activity — your report count, points balance, and badge progress.</Bullet>
          </Section>

          <Section title="3. HOW AND WHY WE USE YOUR DATA">
            <Body>We use your data to provide the app's core features:</Body>
            <Bullet>To authenticate you and manage your account.</Bullet>
            <Bullet>To send you warden alerts when a sighting is reported near your parked car.</Bullet>
            <Bullet>To display your username and points on the leaderboard and thank-you screens.</Bullet>
            <Bullet>To calculate alert radius matching and determine which users to notify.</Bullet>
            <Bullet>To award points and track badges for your contributions.</Bullet>
            <Body>Our legal basis for processing is the performance of a contract (providing the app service you signed up for), and where applicable, legitimate interests in operating a community safety network.</Body>
          </Section>

          <Section title="4. WHO WE SHARE YOUR DATA WITH">
            <Body>We do not sell your data. We share limited data with the following trusted service providers only to the extent necessary to operate the app:</Body>
            <Bullet>
              Supabase Inc. — our database and authentication provider. Your account data, location reports, and profile information are stored securely on Supabase infrastructure. Supabase is SOC 2 Type 2 certified. Data may be stored in the EU or US. See supabase.com/privacy.
            </Bullet>
            <Bullet>
              Google Firebase (FCM) — used to deliver push notifications to your device. Only your device push token is shared with Firebase for this purpose. See firebase.google.com/support/privacy.
            </Bullet>
            <Bullet>
              Google Maps — the warden reporting screen uses Google Maps to display a map and your real-time location (as a blue dot). When this screen is open, the Google Maps SDK may transmit your device's location and usage data to Google in accordance with Google's privacy policy. See policies.google.com/privacy.
            </Bullet>
            <Body>We may disclose data if required by law or to protect the safety of users.</Body>
          </Section>

          <Section title="5. LOCATION AND CAMERA DATA">
            <Body>
              Location data is collected only when you actively use the app — when you activate parking protection or submit a warden report. We do not track your location in the background at any other time. Location coordinates are stored to enable alert matching and are not used for advertising or profiling.
            </Body>
            <Body>
              Camera access is requested when you choose to photo-verify a warden report. The photo itself is never uploaded to our servers — only a boolean flag (verified: yes/no) is stored. Your photo stays on your device.
            </Body>
            <Body>
              When you open the warden reporting screen, the Google Maps SDK displays a map using your live location. This is processed by Google as described in section 4.
            </Body>
          </Section>

          <Section title="6. HOW LONG WE KEEP YOUR DATA">
            <Bullet>Account data (email, username) — retained for as long as your account is active.</Bullet>
            <Bullet>Location and warden report data — retained for 90 days, then automatically deleted.</Bullet>
            <Bullet>Push tokens — retained while your account is active and refreshed automatically.</Bullet>
            <Bullet>Profile photo — retained until you replace or delete it.</Bullet>
            <Body>If you delete your account, all personal data is permanently removed within 30 days.</Body>
          </Section>

          <Section title="7. YOUR RIGHTS">
            <Body>Under UK GDPR you have the right to:</Body>
            <Bullet>Access — request a copy of the personal data we hold about you.</Bullet>
            <Bullet>Rectification — ask us to correct inaccurate data.</Bullet>
            <Bullet>Erasure — ask us to delete your account and all associated data.</Bullet>
            <Bullet>Restriction — ask us to limit how we use your data.</Bullet>
            <Bullet>Portability — receive your data in a machine-readable format.</Bullet>
            <Bullet>Objection — object to processing based on legitimate interests.</Bullet>
            <Body>
              To exercise any of these rights, email us at contact@doubleyellow.app. We will respond within 30 days. You also have the right to lodge a complaint with the Information Commissioner's Office (ICO) at ico.org.uk.
            </Body>
          </Section>

          <Section title="8. CHILDREN">
            <Body>
              Double Yellow is not directed at children under the age of 13. We do not knowingly collect data from children. If you believe a child has provided us with personal data, please contact us and we will delete it promptly.
            </Body>
          </Section>

          <Section title="9. CHANGES TO THIS POLICY">
            <Body>
              We may update this policy from time to time. When we do, we will update the "Last updated" date at the top of this page. Continued use of the app after changes constitutes acceptance of the updated policy.
            </Body>
          </Section>

          <Section title="10. CONTACT">
            <Body>
              For any privacy questions or data requests, contact us at: contact@doubleyellow.app
            </Body>
          </Section>

          <View style={{ height: 40 }} />
        </View>
      </ScrollView>

    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0D0D0D' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 16,
  },
  backText: { fontSize: 12, fontWeight: '700', color: '#666666', letterSpacing: 2 },
  headerTitle: { fontSize: 14, fontWeight: '900', color: '#FFFFFF', letterSpacing: 3 },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 24, paddingTop: 8, gap: 20 },
  updated: { fontSize: 11, color: '#444444', letterSpacing: 1, marginBottom: 4 },
  section: { gap: 10 },
  sectionTitle: { fontSize: 11, fontWeight: '900', color: '#FFD700', letterSpacing: 3, marginBottom: 2 },
  body: { fontSize: 13, color: '#AAAAAA', lineHeight: 22, letterSpacing: 0.3 },
  bulletRow: { flexDirection: 'row', gap: 10, paddingLeft: 4 },
  bulletDot: { fontSize: 16, color: '#FFD700', lineHeight: 22, marginTop: 1 },
  bulletText: { flex: 1, fontSize: 13, color: '#AAAAAA', lineHeight: 22, letterSpacing: 0.3 },
});
